config/routes.rb
Rails.application.routes.draw do
 

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'artists#index'
  resources :artists, :artworks
  get "artists", to: "artists#index"

  get "artists/new", to: "artists#new" #new


  get "artists/:id/edit", to: "artists#edit", as: :artist_edit #Edit page

  patch "artists/:id/update", to: "artists#update"

  delete "artists/:id", to: "artists#destroy"

  post "artists", to: "artists#create"# cuz we're creating a new artist 
  get "artists/:id", to: "artists#show" # , as: :artist  #show


  get "artworks", to: "artworks#index"

  get "artworks/new", to: "artworks#new"

  post "artworks", to: "artworks#create"

  get "artworks/:id/edit", to: "artworks#edit", as: :artwork_edit #Edit page

  patch "artworks/:id/update", to: "artworks#update"

  delete "artworks/:id", to: "artworks#destroy"

end

app/models/artist.rb
class Artist < ApplicationRecord
    # belongs_to :user
    has_many :artworks, dependent: :destroy
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

    before_action :authenticate_user!

    def index 
        @artists = Artist.all
        @artist = Artist.where(user_id: current_user.id)
    end

    def edit
        @artist = Artist.find(params[:id])
    end

    def show 
        @artist = Artist.find(params[:id])
        @artworks = @artist.artworks
    end

    def new
        @artist = Artist.new
    end

    def create
        # @artist.user_id = current_user.id
        @artist = Artist.new(params.require(:artist).permit(:name, :age, :style, :img))
        Artist.create(params.require(:artist).permit(:name, :age, :style, :img))
        redirect_to artists_path #artist path = index
    end

    #def destroy
       # Artist.find(params[:id]).destroy
      
        #redirect_to artists_path
    #end

    def update
        artist = Artist.find(params[:id])
        artist.update(params.require(:artist).permit(:name, :age, :style, :img))
          
        redirect_to artists_path
    end

    def destroy   
        @artist = Artist.find(params[:id]).destroy  
        if @artist.delete   
          flash[:notice] = 'Artist deleted!'   
          redirect_to artists_path   
        else   
          flash[:error] = 'Failed to delete this Artist!'   
          render :destroy   
        end   
    end 

end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/_form.html.erb
<%= form_for @artist do |f| %>
    <div class="input-field col s6 white">
        <%= f.label :img, 'Image'%>
        <%= f.text_field :img%>
    </div>
    <div class="input-field col s6 white">
        <%= f.label :name, 'Name'%>
        <%= f.text_field :name%>
    </div>
    <div class="input-field col s6 white">
        <%= f.label :age, 'Age' %>
        <%= f.text_field :age %>
    </div>
    <div class="input-field col s6 white">
        <%= f.label :style, 'Style' %>
        <%= f.text_field :style %>
    </div>
    <%= f.submit "Submit", :class => "btn waves-effect waves-light white" %>
  <% end %>

app/views/artists/edit.html.erb
<h1 class='white'>Edit <%= @artist.name %>'s Info</h1>

<%= render 'artists/form' %> 

app/views/artists/index.html.erb
<br>
<h1 class='white'> An Art Gallery</h1> <h1 class='white'>Where You Can View Your Favourite</h1><h1 class='white'> Artists And Thier Artwork</h1>

<br><br>

<% if current_user.email == "fatmakelantan@outlook.com"%>
<div class='brown'><%= link_to "",  new_artist_path,  class: "glyphicon glyphicon-plus-sign text-secondary" %>Add a new Artist</div> 
<% end %>

<div class="table-responsive">
<table class="striped bordered table">

   
    <tr>
    <% @artists.each do |a| %>
        
            <td>
            <div class='facts-box text-center'>
            <div ><%= link_to a.name, artist_path(a), class:'title highlighted' %></div>
            <div><%= image_tag(a.img, size: "150x200", alt: "Artist Photo", class:"rounded mx-auto d-block") %></div>
            <div class='brown'><%= a.age %></div>
            <div class='brown'><%= a.style %></div>
            <hr/>
         <% if current_user.email == "fatmakelantan@outlook.com"%>
            <div><%= link_to "", edit_artist_path(a),  class:"glyphicon glyphicon-edit text-secondary" %>
            <%= link_to "", artist_path(a), class: "glyphicon glyphicon-trash text-secondary", :method => :delete, data: { confirm: "Are you sure?" }%></div>
         <% end %>
         </div>
            </td>
        
    <% end %>
    </tr>
    
</table>
</div>

app/views/artists/new.html.erb
<h1 class='white'>New Artist</h1>

<%= render 'artists/form' %>

app/views/artists/show.html.erb
<br>
<h1 class='white'><%= @artist.name %>'s Artwork</h1>
<br><br>

<% if current_user.email == "fatmakelantan@outlook.com"%>
<div class='brown'><%= link_to " New Artwork" , new_artwork_path(:Artist_id => @artist.id), class: "glyphicon glyphicon-plus-sign text-secondary"%></div>
<% end %>


<div class="table-responsive">
<table class="striped bordered table">

 <tr>
    <% @artist.artworks.each do |artwork| %>
        <td>
            <div class='facts-box text-center'>
            <div class='highlighted'><%= artwork.title %></div>
            <div><%= image_tag(artwork.img, size: "100x100", alt: "Painting Image") %></div>
            <div class='brown'><%= artwork.date %></div>
            <div class='brown'><%= artwork.artwork_type %></div>
            <div class='brown'><%= artwork.price %></div>
            <hr/>
        <% if current_user.email == "fatmakelantan@outlook.com" %>
            <div><%= link_to "", artwork_edit_path(artwork.id,:Artist_id => @artist.id), class: "glyphicon glyphicon-edit"%>
            <%= link_to "", artist_path(artwork), class: "glyphicon glyphicon-trash", :method => :delete, data: { confirm: "Are you sure?" }%></div>
        <% end %>
            </div>
        </td>
    <% end %>
   </tr> 
</table>

<%= link_to 'Back', artists_path, class: 'glyphicon glyphicon-chevron-left highlighted'%>